permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

# 作者信息
author: 
  name: frkhit
  email: frkhit@gmail.com
  link: https://blog.arkfeng.xyz
  github: https://github.com/frkhit

# 站点信息
title: 日志
description: blog for frkhit
url: https://blog.arkfeng.xyz
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/avatar.png
favicon: /public/img/avatar.png

# google analytics 设置
ga:
 id: UA-143320942-1
 url: blog.arkfeng.xyz

# disqus 设置
#disqus:
# shortname: blog-arkfeng-xyz

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates:
  - python
  - ubuntu

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

# 插件
plugins:
  - hook-add-last-modified-date
