permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: frkhit
  email: frkhit@gmail.com
  link: http://frkhit.github.io
  github: http://github.com/frkhit

# 站点信息
title: 日志
description: blog for frkhit
url: https://frkhit.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
#gavatar: /public/img/deer3.png
#favicon: /public/img/deer3.png

# google analytics 设置
#ga:
#  id: UA-54262064-1
#  url: painterlin.com

# disqus 设置
#disqus:
#  shortname: painterlin

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates:
  - python
  - ubuntu

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档